### ISSUE TITLE
class "codechicken.core.launch.CodeChickenCorePlugin"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by enricotagliavini** [TheCBProject/CodeChickenCore#11]
Today I updated CodeChicken core to version 1.10.2-2.4.0.100-universal and CodeChicken Libs to version 1.10.2-2.5.0.178-universal. This makes both client and server to crash at startup. Report of the client below.

For the time being I downgrade to CodeChicken Lib 1.10.2-2.4.3.124-universal and CodeChicken Core 1.10.2-2.3.5.91-universal (the previous versions I had). Minecraft starts as expected.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 18/12/16 17:57
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Core (CodeChickenCore)
Caused by: java.lang.ClassNotFoundException: codechicken.core.launch.CodeChickenCorePlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:505)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.SecurityException: class "codechicken.core.launch.CodeChickenCorePlugin"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 4.8.14-200.fc24.x86_64
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 208320672 bytes (198 MB) / 400482304 bytes (381 MB) up to 2398355456 bytes (2287 MB)
	JVM Flags: 5 total; -Xmx2300M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151.jar) 
	UC	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151.jar) 
	UC	NotEnoughItems{2.1.2.163} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.163-universal.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UC	battletowers{1.5.5} [Battle Towers] (BattleTowers-1.10.2.jar) 
	UC	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UC	XaeroBetterPvP{1.11.7} [Better PVP Fair-Play Mod] (BetterPvPFairPlay_1.11.7_Forge_1.10.2.jar) 
	UC	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UC	boatlantern{1.10.2-0.2.1} [Lantern] (boatlantern-0.2.1.jar) 
	UC	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UC	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UC	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UC	ChestTransporter{2.5.6} [Chest Transporter] (ChestTransporter-1.10.2-2.5.6.jar) 
	UC	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UE	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UC	drpcore{0.1.7} [Dark Roleplay Core] (Dark Roleplay Core 0.1.7.jar) 
	UC	drpmedieval{0.1.6} [Dark Roleplay Medieval] (Dark Roleplay Medieval-0.1.6.jar) 
	UC	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UC	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UC	JEI{3.13.6.392} [Just Enough Items] (jei_1.10.2-3.13.6.392.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	EnderIO{1.10.2-3.0.1.142_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.142_beta.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.0.jar) 
	UC	forestry{5.2.16.328} [Forestry] (forestry_1.10.2-5.2.16.328.jar) 
	UC	InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.10-1.4.9.jar) 
	UC	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UC	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UC	journeymap{1.10.2-5.3.0} [JourneyMap] (journeymap-1.10.2-5.3.0.jar) 
	UC	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UC	minecolonies{1.10.2-0.6.2038} [MineColonies] (minecolonies-universal-1.10.2-0.6.2038.jar) 
	UC	parachutemod{1.5.2} [Parachute Mod] (parachutemod-ng-1.10.2-1.5.2-416.jar) 
	UC	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UC	AS_Ruins{16.2} [Ruins Spawning System] (Ruins-1.10.2.jar) 
	UC	sgcraft{1.13.0} [SG Craft] (SGCraft-1.13.0-mc1.10.2.jar) 
	UC	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UC	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UC	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.163-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 367.57' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)
```

**Comment by covers1624** [comment]
Update brandons core.

**Comment by enricotagliavini** [comment]
Argh I missed Brandon's Core was depending on CodeChicken libs, sorry. Dependencies handling is a mess ;)

**Comment by covers1624** [comment]
All good.
