### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by QA-San** [TheCBProject/CodeChickenCore#3]
1.10.2-forge1.10.2-12.18.1.2060
CodeChickenCore-1.10.2-2.1.8.79-universal
CodeChickenLib-1.10.2-2.2.3.58-universal

CodeChickenCore.cfg
	#Set this to true to use the pre1.5 lava textures
	replaceLavaFX=true
	#Set this to true to use the pre1.5 water textures
	replaceWaterFX=true

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCCDeobfPlugin (unknown)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 16/08/14 10:01
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 0
	at codechicken.core.featurehack.mc.TextureLavaFlowFX.writeColour(TextureLavaFlowFX.java:114)
	at codechicken.core.featurehack.mc.TextureLavaFlowFX.onTick(TextureLavaFlowFX.java:106)
	at codechicken.lib.render.TextureFX.update(TextureFX.java:50)
	at codechicken.lib.render.TextureSpecial.func_94219_l(TextureSpecial.java:72)
	at net.minecraft.client.renderer.texture.TextureMap.func_94248_c(TextureMap.java:328)
	at net.minecraft.client.renderer.texture.TextureMap.func_110550_d(TextureMap.java:354)
	at net.minecraft.client.renderer.texture.TextureManager.func_110550_d(TextureManager.java:124)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1672)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3578146744 bytes (3412 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4G -Xmx4G -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2060 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2060.jar) 
	UCHIJA	Forge{12.18.1.2060} [Minecraft Forge] (forge-1.10.2-12.18.1.2060.jar) 
	UCHIJA	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
CCCDeobfPlugin (unknown)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.81' Renderer: 'GeForce GT 650M/PCIe/SSE2'
	CodeChickenCore: ignoreInvalidMCVersion state: false
	Launched Version: 1.10.2-forge1.10.2-12.18.1.2060
	LWJGL: 2.9.4
	OpenGL: GeForce GT 650M/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.81, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (United Kingdom)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz

**Comment by covers1624** [comment]
The lava and water fx stuff is being moved to another mod, dissable it.
